name: wigilabs_test
description: "Flutter app to consume REST Countries API with wishlist functionality using BLoC, Drift, and Dio."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HTTP & Caching
  dio: ^5.9.1
  dio_cache_interceptor: ^4.0.5

  # State Management
  flutter_bloc: ^8.1.4
  bloc: ^8.1.2

  # Database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3

  # Dependency Injection
  get_it: ^7.6.0

  # Serialization
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # UI & Utils
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  connectivity_plus: ^7.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Testing
  flutter_lints: ^3.0.0
  mocktail: ^1.0.0
  bloc_test: ^9.1.0

  # Code Generation
  build_runner: ^2.4.6
  drift_dev: ^2.14.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
